name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
   
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: weather_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
     
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
     
      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    - name: Set up environment variables
      run: |
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "DB_NAME=weather_test_db" >> $GITHUB_ENV
        echo "DB_USER=postgres" >> $GITHUB_ENV
        echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV
        echo "REDIS_HOST=localhost" >> $GITHUB_ENV
        echo "REDIS_PORT=6379" >> $GITHUB_ENV
        echo "REDIS_DB=1" >> $GITHUB_ENV
        echo "WEATHER_API_KEY=test_key_12345" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=test@example.com" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=test_password" >> $GITHUB_ENV
        echo "DEFAULT_FROM_EMAIL=test@example.com" >> $GITHUB_ENV
   
    - name: Make migrations
      run: |
        python manage.py makemigrations --settings=weather_project.settings_ci
   
    - name: Run migrations
      run: |
        python manage.py migrate --settings=weather_project.settings_ci
   
    - name: Run tests
      run: |
        python manage.py test --settings=weather_project.settings_ci --verbosity=2
   
    - name: Check code style
      run: |
        python manage.py check --settings=weather_project.settings_ci

